---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: binaryfile
              emptyDir: {}
            - name: graveyard
              emptyDir: {}
          initContainers:
          - name: kubexit
            image: karlkfi/kubexit:0.3.2
            command: ['cp', '/bin/kubexit', '/kubexit/kubexit']
            volumeMounts:
            - mountPath: /kubexit
              name: binaryfile
          containers:
          - name: main
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c']
            args:
            - |
              /kubexit/kubexit sleep 10
            volumeMounts:
            - mountPath: /kubexit
              name: binaryfile
            - mountPath: /graveyard
              name: graveyard
            env:
            - name: "KUBEXIT_NAME"
              value: "main"
            - name: KUBEXIT_GRAVEYARD
              value: /graveyard
            - name: KUBEXIT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBEXIT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          - name: sidecar
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c']
            args:
            - |
              /kubexit/kubexit sleep 666666
            volumeMounts:
            - mountPath: /kubexit
              name: binaryfile
            - mountPath: /graveyard
              name: graveyard
            env:
            - name: "KUBEXIT_NAME"
              value: "sidecar"
            - name: KUBEXIT_GRAVEYARD
              value: /graveyard
            - name: KUBEXIT_DEATH_DEPS
              value: main
            - name: KUBEXIT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBEXIT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          restartPolicy: Never
